import os
import psycopg2


def drop_user_db(conn):
    conn.autocommit = True
    cur = conn.cursor()

    cur.execute("DROP TABLE IF EXISTS bd_users CASCADE;")
def init_user_db(conn):
    conn.autocommit = True
    cur = conn.cursor()

    cur.execute("DROP TABLE IF EXISTS bd_users CASCADE;")


    cur.execute(query='''
        CREATE TABLE bd_users (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 20),
        login VARCHAR (30) NOT NULL UNIQUE,
        email VARCHAR (50) NOT NULL,
        password TEXT NOT NULL,
        countryCode VARCHAR (2) NOT NULL,
        isPablic BOOLEAN,
        phone VARCHAR (12),
        image TEXT,
        token TEXT
    );
    ''')

