
def drop_friend_db(conn):
    conn.autocommit = True
    cur = conn.cursor()

    cur.execute("DROP TABLE IF EXISTS friendship;")
def init_friend_db(conn):
    conn.autocommit = True
    cur = conn.cursor()

    cur.execute("DROP TABLE IF EXISTS friendship;")


    cur.execute('''
    CREATE TABLE friendship (
    count integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 20), 
    user_login1 VARCHAR NOT NULL,
    user_login2 VARCHAR NOT NULL,
    timeFR TIMESTAMP NOT NULL,
    FOREIGN KEY (user_login1) REFERENCES bd_users (login),
    FOREIGN KEY (user_login2) REFERENCES bd_users (login),
    UNIQUE (user_login1, user_login2)
    );
    ''')

# CREATE TABLE ClassStudentRelation(
#     StudentID varchar2(15) NOT NULL,
#     ClassID varchar2(14) NOT NULL,
#     FOREIGN KEY (StudentID) REFERENCES Student(StudentID),
#     FOREIGN KEY (ClassID) REFERENCES Class(ClassID),
#     UNIQUE (StudentID, ClassID)
# );